[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
